import streamlit as st
from fpdf import FPDF
import base64
import os
import json

def create_pdf(profile, history, summary="", symptom_data=None):
    pdf = FPDF()
    pdf.add_page()
    
    # Professional Header
    pdf.set_fill_color(30, 27, 75) # Deep Blue
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 24)
    pdf.cell(0, 20, 'MEDIBOT HEALTH REPORT', ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, 'Your Personalized AI Health Assessment Summary', ln=True, align='C')
    pdf.ln(20)
    
    pdf.set_text_color(0, 0, 0)
    
    # 1. User Profile Section
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 10, ' 1. Patient Information', ln=True, fill=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", '', 10)
    if profile:
        col_width = 95
        items = list(profile.items())
        for i in range(0, len(items), 2):
            k1, v1 = items[i]
            line = f"{k1.capitalize()}: {v1}"
            if i+1 < len(items):
                k2, v2 = items[i+1]
                pdf.cell(col_width, 10, line)
                pdf.cell(col_width, 10, f"{k2.capitalize()}: {v2}", ln=True)
            else:
                pdf.cell(0, 10, line, ln=True)
    else:
        pdf.cell(0, 10, "No profile data recorded.", ln=True)
    pdf.ln(10)

    # 2. Comprehensive Health Summary
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, ' 2. AI Medical Summary', ln=True, fill=True)
    pdf.ln(5)
    pdf.set_font("Arial", '', 11)
    if summary:
        pdf.multi_cell(0, 8, summary.encode('latin-1', 'replace').decode('latin-1'))
    else:
        pdf.cell(0, 10, "Summary generation skipped or no data available.", ln=True)
    pdf.ln(10)
    
    # 3. Symptom Checker Results
    if symptom_data:
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, ' 3. Symptom Analysis Results', ln=True, fill=True)
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(0, 10, f"Symptoms: {', '.join(symptom_data.get('symptoms', []))}", ln=True)
        pdf.cell(0, 10, f"Duration: {symptom_data.get('duration')} days | Severity: {symptom_data.get('severity')}", ln=True)
        pdf.ln(2)
        pdf.set_font("Arial", '', 10)
        pdf.multi_cell(0, 8, symptom_data.get('analysis', '').encode('latin-1', 'replace').decode('latin-1'))
        pdf.ln(10)

    # 4. Consultation History (Concise)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, ' 4. Interaction History', ln=True, fill=True)
    pdf.ln(5)
    pdf.set_font("Arial", '', 9)
    if history:
        for chat in history[-10:]: # Show last 10 messages for brevity
            role = "Patient" if chat['role'] == "user" else "MediBot"
            content = chat['content'].encode('latin-1', 'replace').decode('latin-1') 
            pdf.set_font("Arial", 'B', 9)
            pdf.cell(0, 6, f"{role}:", ln=True)
            pdf.set_font("Arial", '', 9)
            pdf.multi_cell(0, 6, content)
            pdf.ln(2)
    else:
        pdf.cell(0, 10, "No consultation history recorded.", ln=True)
        
    # Footer & Disclaimer
    pdf.set_y(-30)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(100, 100, 100)
    disclaimer = "DISCLAIMER: This report is generated by an AI assistant for informational purposes only. It is NOT a medical diagnosis or prescription. Please consult a qualified healthcare professional for any medical concerns."
    pdf.multi_cell(0, 5, disclaimer, align='C')
    
    return pdf.output(dest="S")

def generate_comprehensive_summary(profile, history, symptom_data):
    """Generates a professional medical summary combining all data."""
    import os
    from langchain_openai import ChatOpenAI
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return ""
    
    try:
        llm = ChatOpenAI(temperature=0, openai_api_key=api_key, base_url="https://api.groq.com/openai/v1", model_name="llama-3.1-8b-instant")
        
        context = f"""
        PROFILE: {profile}
        SYMPTOMS: {symptom_data.get('symptoms') if symptom_data else 'None reported'}
        ANALYSIS: {symptom_data.get('analysis') if symptom_data else 'None'}
        CHAT HISTORY: {history[-5:] if history else 'None'}
        """
        
        prompt = f"As a professional medical AI, provide a 4-5 sentence clinical summary of the user's health profile, current symptoms, and primary concerns discussed in the chat. Use formal medical terminology and be concise. Do not diagnose.\n\nCONTEXT:\n{context}"
        
        response = llm.invoke(prompt)
        return response.content
    except Exception as e:
        return f"Summary generation unavailable: {str(e)}"

def render_reports():
    st.markdown("### :material/analytics: Professional Health Reports")
    st.markdown("Generate a comprehensive PDF documentation of your health profile, AI consultations, and symptom analysis.")
    
    # Load data
    profile = st.session_state.get('user_profile', {})
    history = st.session_state.get('history', [])
    symptom_data = st.session_state.get('latest_analysis')
    
    if st.button("Generate Professional PDF", icon=":material/picture_as_pdf:", type="primary", use_container_width=True):
        if not profile and not history and not symptom_data:
            st.warning("No data found. Please complete your profile or start a chat first.")
        else:
            with st.spinner("Synthesizing your health data into a professional report..."):
                try:
                    summary = generate_comprehensive_summary(profile, history, symptom_data)
                    pdf_bytes = create_pdf(profile, history, summary, symptom_data)
                    
                    b64 = base64.b64encode(pdf_bytes).decode()
                    href = f'''
                        <div style="text-align: center; margin-top: 20px;">
                            <a href="data:application/octet-stream;base64,{b64}" download="MediBot_Health_Report.pdf" 
                               style="background-color: #4F46E5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 12px; font-weight: bold; display: inline-block;">
                               Download Official PDF Report
                            </a>
                        </div>
                    '''
                    st.success("Report synthesized successfully!")
                    st.markdown(href, unsafe_allow_html=True)
                    
                except Exception as e:
                    st.error(f"Error generating PDF: {str(e)}")

    st.markdown("---")
    st.markdown("#### :material/bar_chart: Simple Analytics")
    
    if history:
        st.metric("Total Interactions", len(history))
        user_msgs = len([x for x in history if x['role'] == 'user'])
        st.metric("Questions Asked", user_msgs)
    else:
        st.info("Start chatting to see analytics.")
